// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Datepicker: typeof import('./src/components/Datepicker.vue')['default']
    FlashMessage: typeof import('./src/components/FlashMessage.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    RegisterAccountLinks: typeof import('./src/components/RegisterAccountLinks.vue')['default']
    RegisterActions: typeof import('./src/components/RegisterActions.vue')['default']
    SSOLogin: typeof import('./src/components/SSOLogin.vue')['default']
    TheCheckbox: typeof import('./src/components/TheCheckbox.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheRadio: typeof import('./src/components/TheRadio.vue')['default']
    TheSelect: typeof import('./src/components/TheSelect.vue')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    'Mdi:checkboxMarkedOutline': typeof import('virtual:vite-icons/mdi/checkbox-marked-outline')['default']
    'Mdi:checkboxBlankOutline': typeof import('virtual:vite-icons/mdi/checkbox-blank-outline')['default']
    JamCloseCircleF: typeof import('virtual:vite-icons/jam/close-circle-f')['default']
    'Ic:roundMenu': typeof import('virtual:vite-icons/ic/round-menu')['default']
    'Ic:roundAccountCircle': typeof import('virtual:vite-icons/ic/round-account-circle')['default']
    'Mdi:loading': typeof import('virtual:vite-icons/mdi/loading')['default']
    'Mdi:chevronDoubleLeft': typeof import('virtual:vite-icons/mdi/chevron-double-left')['default']
    'Mdi:chevronDoubleRight': typeof import('virtual:vite-icons/mdi/chevron-double-right')['default']
  }
}

export { }
