// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/atoms/AppButton.vue')['default']
    AppContainer: typeof import('./src/components/atoms/AppContainer.vue')['default']
    AppLabel: typeof import('./src/components/atoms/AppLabel.vue')['default']
    AppLink: typeof import('./src/components/atoms/AppLink.vue')['default']
    AppTitle: typeof import('./src/components/atoms/AppTitle.vue')['default']
    AuthLayout: typeof import('./src/components/atoms/AuthLayout.vue')['default']
    IconLoading: typeof import('./src/components/atoms/IconLoading.vue')['default']
    FlashMessage: typeof import('./src/components/global/FlashMessage.vue')['default']
    AppCheckbox: typeof import('./src/components/molecules/AppCheckbox.vue')['default']
    AppInput: typeof import('./src/components/molecules/AppInput.vue')['default']
    AppPopover: typeof import('./src/components/molecules/AppPopover.vue')['default']
    AppRadio: typeof import('./src/components/molecules/AppRadio.vue')['default']
    AppSelect: typeof import('./src/components/molecules/AppSelect.vue')['default']
    Card: typeof import('./src/components/organisms/Card.vue')['default']
    Datepicker: typeof import('./src/components/organisms/Datepicker.vue')['default']
    FormActions: typeof import('./src/components/organisms/FormActions.vue')['default']
    NotFound: typeof import('./src/components/templates/NotFound.vue')['default']
    TheHeader: typeof import('./src/components/templates/TheHeader.vue')['default']
    AccountResetPasswordForm: typeof import('./src/components/templates/account/ResetPasswordForm.vue')['default']
    ApplyCurrentInfo: typeof import('./src/components/templates/apply/CurrentInfo.vue')['default']
    ApplySupplyList: typeof import('./src/components/templates/apply/SupplyList.vue')['default']
    ApplyToolbar: typeof import('./src/components/templates/apply/Toolbar.vue')['default']
    HomeCardList: typeof import('./src/components/templates/home/CardList.vue')['default']
    LoginFormInput: typeof import('./src/components/templates/login/FormInput.vue')['default']
    LoginRegisterLinks: typeof import('./src/components/templates/login/RegisterLinks.vue')['default']
    LoginSSOButtons: typeof import('./src/components/templates/login/SSOButtons.vue')['default']
    LoginTitle: typeof import('./src/components/templates/login/Title.vue')['default']
    RegisterDonator: typeof import('./src/components/templates/register/Donator.vue')['default']
    RegisterDonatorTitle: typeof import('./src/components/templates/register/DonatorTitle.vue')['default']
    RegisterOrg: typeof import('./src/components/templates/register/Org.vue')['default']
    RegisterOrgTitle: typeof import('./src/components/templates/register/OrgTitle.vue')['default']
    'Ic:roundMenu': typeof import('virtual:vite-icons/ic/round-menu')['default']
    'Ic:roundAccountCircle': typeof import('virtual:vite-icons/ic/round-account-circle')['default']
    JamCloseCircleF: typeof import('virtual:vite-icons/jam/close-circle-f')['default']
    'Mdi:checkboxMarkedOutline': typeof import('virtual:vite-icons/mdi/checkbox-marked-outline')['default']
    'Mdi:checkboxBlankOutline': typeof import('virtual:vite-icons/mdi/checkbox-blank-outline')['default']
    'Mdi:loading': typeof import('virtual:vite-icons/mdi/loading')['default']
    'Mdi:chevronDoubleLeft': typeof import('virtual:vite-icons/mdi/chevron-double-left')['default']
    'Mdi:chevronDoubleRight': typeof import('virtual:vite-icons/mdi/chevron-double-right')['default']
  }
}

export { }
